/*
 * generated by Xtext 2.22.0
 */
package bag.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractBagDslScopeProvider extends DelegatingScopeProvider {
}
