/*
 * generated by Xtext 2.17.0
 */
package bag


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class DSLRuntimeModule extends AbstractDSLRuntimeModule {
}
