/*
 * generated by Xtext 2.22.0
 */
package bag.dsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class BagDslRuntimeModule extends AbstractBagDslRuntimeModule {
}
