/**
 * generated by Xtext 2.22.0
 */
package bag.ide;

import bag.DSLRuntimeModule;
import bag.DSLStandaloneSetup;
import bag.ide.DSLIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class DSLIdeSetup extends DSLStandaloneSetup {
  @Override
  public Injector createInjector() {
    DSLRuntimeModule _dSLRuntimeModule = new DSLRuntimeModule();
    DSLIdeModule _dSLIdeModule = new DSLIdeModule();
    return Guice.createInjector(Modules2.mixin(_dSLRuntimeModule, _dSLIdeModule));
  }
}
