/**
 * generated by Xtext 2.22.0
 */
package bag.ide;

import bag.ide.AbstractDSLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class DSLIdeModule extends AbstractDSLIdeModule {
}
