/*
 * generated by Xtext 2.22.0
 */
package bag.dsl.ide;

import bag.dsl.BagDslRuntimeModule;
import bag.dsl.BagDslStandaloneSetup;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class BagDslIdeSetup extends BagDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new BagDslRuntimeModule(), new BagDslIdeModule()));
	}
	
}
