/**
 * generated by Xtext 2.22.0
 */
package bag.ui.contentassist;

import bag.ui.contentassist.AbstractDSLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class DSLProposalProvider extends AbstractDSLProposalProvider {
}
