/*
 * generated by Xtext 2.22.0
 */
package bag.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class BagDslUiModule extends AbstractBagDslUiModule {

	public BagDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
