/*
 * generated by Xtext 2.22.0
 */
package bag.dsl;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class BagDslStandaloneSetup extends BagDslStandaloneSetupGenerated {

	public static void doSetup() {
		new BagDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
