/**
 * generated by Xtext 2.17.0
 */
package bag;

import bag.AbstractDSLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class DSLRuntimeModule extends AbstractDSLRuntimeModule {
}
