/**
 * generated by Xtext 2.17.0
 */
package bag;

import bag.DSLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class DSLStandaloneSetup extends DSLStandaloneSetupGenerated {
  public static void doSetup() {
    new DSLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
